# Tests

In [5]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("multi-qa-MiniLM-L6-cos-v1")

query_embedding = model.encode("How big is London")
passage_embedding = model.encode([
    "Es una ciudad muy grande",
    "My name is Vitor"
])

print("Similarity:", util.dot_score(query_embedding, passage_embedding))

C:\Users\voliveira\OneDrive - Corporacion Empresarial Altra SL\00-Proyectos\myzone\.venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\voliveira\OneDrive - Corporacion Empresarial Altra SL\00-Proyectos\myzone\.venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


Similarity: tensor([[ 0.0906, -0.0839]])


In [6]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [7]:
model2 = SentenceTransformer("multi-qa-mpnet-base-cos-v1")

C:\Users\voliveira\OneDrive - Corporacion Empresarial Altra SL\00-Proyectos\myzone\.venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [8]:
query_embedding = model2.encode("How big is London")
passage_embedding = model2.encode([
    "Es una ciudad muy grande",
    "My name is Vitor",
    "London is a big city"
])

print("Similarity:", util.dot_score(query_embedding, passage_embedding))

Similarity: tensor([[ 0.2261, -0.0325,  0.8085]])


In [9]:
query_embedding.shape

(768,)

In [10]:
incidencias_embedding = model2.encode([
    "PANTALLA TACTIL NO VA BIEN.  PANTALLA TACTIL NO FUNCIONA CORRECTAMENTE. AZC3BLUEFECOSB"
])

errors_embedding = model2.encode([
    "Fallo de comunicaciones El termostato no comunica con la central o no se puede asociar.",
    "Fallo de pantalla Hay un fallo estético en la pantalla, no se representan bien las imágenes.",
    "No funciona el táctil El termostato representa imágenes y reacciona cuando se quita y pone alimentación, pero las pulsaciones funcionan mal o no funcionan"
])

In [11]:
def calculate_cosine_similarity(embeddings):
    return util.pytorch_cos_sim(embeddings[0], embeddings[1])

for error in errors_embedding:
    print(calculate_cosine_similarity([incidencias_embedding[0], error]))

tensor([[0.3446]])
tensor([[0.4416]])
tensor([[0.5958]])


In [23]:
model = SentenceTransformer("all-MiniLM-L6-v2")

# Our sentences we like to encode
sentences = [
    "This framework generates embeddings for each input sentence",
    "Sentences are passed as a list of strings.",
    "The quick brown fox jumps over the lazy dog.",
]

# Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

# Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\voliveira\OneDrive - Corporacion Empresarial Altra SL\00-Proyectos\myzone\.venv\lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\voliveira\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence: This framework generates embeddings for each input sentence
Embedding: [-1.37173459e-02 -4.28515412e-02 -1.56286340e-02  1.40537703e-02
  3.95537764e-02  1.21796280e-01  2.94333491e-02 -3.17523852e-02
  3.54959704e-02 -7.93140084e-02  1.75878387e-02 -4.04369757e-02
  4.97259349e-02  2.54912414e-02 -7.18700737e-02  8.14968944e-02
  1.47069071e-03  4.79626954e-02 -4.50336002e-02 -9.92174894e-02
 -2.81769615e-02  6.45046234e-02  4.44670618e-02 -4.76217046e-02
 -3.52952294e-02  4.38671671e-02 -5.28565831e-02  4.33065463e-04
  1.01921521e-01  1.64072327e-02  3.26996520e-02 -3.45987007e-02
  1.21339504e-02  7.94870779e-02  4.58343048e-03  1.57778189e-02
 -9.68203321e-03  2.87625566e-02 -5.05806170e-02 -1.55793717e-02
 -2.87906509e-02 -9.62281413e-03  3.15556787e-02  2.27348804e-02
  8.71449709e-02 -3.85027379e-02 -8.84718746e-02 -8.75498634e-03
 -2.12343261e-02  2.08923612e-02 -9.02077630e-02 -5.25732227e-02
 -1.05638895e-02  2.88310833e-02 -1.61454976e-02  6.17839349e-03
 -1.23234

In [2]:
import pandas as pd

corpus = pd.read_csv("../DATA/processed/2024-05-15/corpus_spanish.csv", sep='¬', engine='python')

corpus.head()

text_to_analyse language
0              NO FUNCIONA  NO FUNCIONA AZC3TACTOCSB       pt
1  DESDE PULSADORES NO SE PUEDE SUBIR LA PERSIANA...       pt
2  REJILLA MOTORIZADA DEFECTUOSA, SUSTITUIR  Rafa...       es
3  Error al pedir la pasarela, a última hora hubo...       es
4  EL TERMOSTATO RADIO E QUEDA BLOQUEADO. SE CONF...       pt

In [13]:
df = corpus.sample(5000)

teste = model2.encode(df['text_to_analyse'].tolist())

In [14]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    print("GPU is available")
    # Get the name of the GPU
    print("GPU name:", torch.cuda.get_device_name(0))
    # Print number of GPUs available
    print("Number of GPUs available:", torch.cuda.device_count())
else:
    print("GPU is not available")

GPU is available
GPU name: Quadro P620
Number of GPUs available: 1
